import React from "react";
import MainLayout from "@/components/mainLayout";
import GeneralContextProvider from "@/providers/generalContext";
import { Typography } from "@mui/material";
import Head from "next/head";

export default function Home() {
  return (
    <>
      <Head>
        <title>Pajhoheshyar</title>
        <meta name="description" content="Generated by Pajhoheshyar" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <MainLayout>
        <Typography component="h1" color="primary">
          Material UI v5 with Next.js in TypeScript
        </Typography>
        <Typography component="h2" color="secondary">
          Boilerplate for building faster.
        </Typography>{" "}
      </MainLayout>
    </>
  );
}
