import React from 'react'
import MainLayout from '@/components/mainLayout'
import GeneralContextProvider from '@/providers/generalContext'
import { Typography } from '@mui/material'
import Head from 'next/head'

export default function Home() {
  return (
    <>
      <Head>
        <title>Pajhoheshyar</title>
        <meta name='description' content='Generated by Pajhoheshyar' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
    </>
  )
}

export const getStaticProps = () => {
  return {
    redirect: {
      permanent: false,
      destination: `/thesis/`,
    },
  }
}
